Locations = ["Italy", "Egypt", "America", "England", "Japan"]
print(f"Original List of locations: {Locations}")
sorted_Locations = sorted(Locations)
print(f"Sorted list of location: {sorted_Locations}")
print(f"Original list of locations: {Locations}")
reversed_Locations = sorted(Locations, reverse=True)
print(f"Reversed Sorted list of locations {reversed_Locations}")
print(f"Original list of locations: {Locations}")
Locations.reverse()
print(Locations)
Locations.reverse()
print(Locations)
Locations.sort()
print(Locations)
Locations.sort(reverse= True)
print(Locations)